// Code generated by Kitex v0.7.2. DO NOT EDIT.

package fileservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	file "github.com/li1553770945/personal-file-service/kitex_gen/file"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UploadFile(ctx context.Context, req *file.UploadFileReq, callOptions ...callopt.Option) (r *file.UploadFileResp, err error)
	DownloadFile(ctx context.Context, req *file.DownloadFileReq, callOptions ...callopt.Option) (r *file.DownloadFileResp, err error)
	DeleteFile(ctx context.Context, req *file.DeleteFileReq, callOptions ...callopt.Option) (r *file.DeleteFileResp, err error)
	FileInfo(ctx context.Context, req *file.FileInfoReq, callOptions ...callopt.Option) (r *file.FileInfoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFileServiceClient struct {
	*kClient
}

func (p *kFileServiceClient) UploadFile(ctx context.Context, req *file.UploadFileReq, callOptions ...callopt.Option) (r *file.UploadFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadFile(ctx, req)
}

func (p *kFileServiceClient) DownloadFile(ctx context.Context, req *file.DownloadFileReq, callOptions ...callopt.Option) (r *file.DownloadFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DownloadFile(ctx, req)
}

func (p *kFileServiceClient) DeleteFile(ctx context.Context, req *file.DeleteFileReq, callOptions ...callopt.Option) (r *file.DeleteFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFile(ctx, req)
}

func (p *kFileServiceClient) FileInfo(ctx context.Context, req *file.FileInfoReq, callOptions ...callopt.Option) (r *file.FileInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FileInfo(ctx, req)
}
