// Code generated by Kitex v0.7.2. DO NOT EDIT.

package fileservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	file "github.com/li1553770945/personal-file-service/kitex_gen/file"
)

func serviceInfo() *kitex.ServiceInfo {
	return fileServiceServiceInfo
}

var fileServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FileService"
	handlerType := (*file.FileService)(nil)
	methods := map[string]kitex.MethodInfo{
		"UploadFile":      kitex.NewMethodInfo(uploadFileHandler, newFileServiceUploadFileArgs, newFileServiceUploadFileResult, false),
		"DownloadFileReq": kitex.NewMethodInfo(downloadFileReqHandler, newFileServiceDownloadFileReqArgs, newFileServiceDownloadFileReqResult, false),
		"DeleteFile":      kitex.NewMethodInfo(deleteFileHandler, newFileServiceDeleteFileArgs, newFileServiceDeleteFileResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "file",
		"ServiceFilePath": `idl\file.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.2",
		Extra:           extra,
	}
	return svcInfo
}

func uploadFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file.FileServiceUploadFileArgs)
	realResult := result.(*file.FileServiceUploadFileResult)
	success, err := handler.(file.FileService).UploadFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFileServiceUploadFileArgs() interface{} {
	return file.NewFileServiceUploadFileArgs()
}

func newFileServiceUploadFileResult() interface{} {
	return file.NewFileServiceUploadFileResult()
}

func downloadFileReqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file.FileServiceDownloadFileReqArgs)
	realResult := result.(*file.FileServiceDownloadFileReqResult)
	success, err := handler.(file.FileService).DownloadFileReq(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFileServiceDownloadFileReqArgs() interface{} {
	return file.NewFileServiceDownloadFileReqArgs()
}

func newFileServiceDownloadFileReqResult() interface{} {
	return file.NewFileServiceDownloadFileReqResult()
}

func deleteFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file.FileServiceDeleteFileArgs)
	realResult := result.(*file.FileServiceDeleteFileResult)
	success, err := handler.(file.FileService).DeleteFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFileServiceDeleteFileArgs() interface{} {
	return file.NewFileServiceDeleteFileArgs()
}

func newFileServiceDeleteFileResult() interface{} {
	return file.NewFileServiceDeleteFileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UploadFile(ctx context.Context, req *file.UploadFileReq) (r *file.UploadFileResp, err error) {
	var _args file.FileServiceUploadFileArgs
	_args.Req = req
	var _result file.FileServiceUploadFileResult
	if err = p.c.Call(ctx, "UploadFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DownloadFileReq(ctx context.Context, req *file.DownloadFileReq) (r *file.DownloadFileResp, err error) {
	var _args file.FileServiceDownloadFileReqArgs
	_args.Req = req
	var _result file.FileServiceDownloadFileReqResult
	if err = p.c.Call(ctx, "DownloadFileReq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFile(ctx context.Context, req *file.DeleteFileReq) (r *file.DeleteFileResp, err error) {
	var _args file.FileServiceDeleteFileArgs
	_args.Req = req
	var _result file.FileServiceDeleteFileResult
	if err = p.c.Call(ctx, "DeleteFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
